FROM golang:1.26-alpine

RUN apk add --no-cache git ca-certificates tzdata make curl unzip

RUN curl -sSL "https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64" -o /usr/local/bin/buf \
    && chmod +x /usr/local/bin/buf

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app/src

EXPOSE 50051
EXPOSE 2345

ENTRYPOINT ["sh", "-c", "cd /workspace && buf generate libs/protos && cd libs/gen/go && go mod init github.com/Kaptoshka/creative-learning-platform/libs/gen/go || true && go mod tidy && cd /app/src && go mod download && air -c .air.toml"]
